---
title: flexTeaching
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    favicon: 'www/favicon.ico'
    logo: 'www/wave.svg'
    css: ["www/fingerprint.css", "www/logo.css", "www/fixes.css", "www/practice.css"]
    includes:
      in_header: !expr flexTeaching:::writeHeaders()
params:
  cache_setup: false
runtime: shiny_prerendered
---

```{r child="children/setup.Rmd"}
```

```{r child="children/query_string.Rmd"}
```

```{r, context="render"}
library(rclipboard)
shiny::includeScript(path = system.file("lib/clipboard.min.js", package = "rclipboard"))
```

```{r context="render"}
shinybusy::add_busy_spinner(spin = "orbit",
                            position = "bottom-right",
                            margins = c(40, 40))
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r child="children/sidebar_main.Rmd"}
```

```{r child="children/sidebar_solve.Rmd"}
```

Column
------------------------------------

```{r context="server"}

validSeed <- reactiveVal({FALSE})

entry <- reactive({
  ifelse(input$entry == TRUE, "solve", "download")
})

seedMatches <- reactiveVal(FALSE)

seed <- reactive({
  
  req(!is.null(input$assignment))

  if(masterseed == "") stop("Master seed cannot be blank!")
  
  salt = all_assignment_data[[input$assignment]]$`seed-salt`
  seed0_masterseed = flexTeaching:::animalSeed(masterseed, salt)

  if(entry()=='solve'){
    seed0 = input$seed
    if(seed0 == seed0_masterseed){
      seedMatches(TRUE)
    }else{
      seedMatches(FALSE)
    }
    return_seed = seed0
  }else{
    seedMatches(FALSE)
    return_seed = seed0_masterseed
  }
  
  return(return_seed)
  
})

solutions <- reactive({
  req(entry())
  input$solutions & (entry() == "solve")
})

```

```{r child="children/content.Rmd"}
```

