---
title: "Check your assignments"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    includes:
      in_header: !expr flexTeaching:::writeHeaders()
runtime: shiny_prerendered
---

```{r child="children/setup.Rmd"}
```

```{r, context="render"}
library(rclipboard)
shiny::includeScript(path = system.file("lib/clipboard.min.js", package = "rclipboard"))
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r child="children/sidebar_main.Rmd"}
```

```{r child="children/sidebar_solve.Rmd"}
```

Column
------------------------------------

```{r context="server"}

init_list = reactive({
  
  req(input$assignment)

  assignment = input$assignment
  assignment_data = all_assignment_data[[assignment]]
    
  id = input$id
  seed = input$seed
  solutions = input$solutions
  
  salt = assignment_data$`data-salt`
  seed0 = flexTeaching:::assignmentSeed(id, seed, salt)
  
  e = new.env()
  
  flexTeaching:::sourceAll(assignment_data, e)
  
  init_func = get(assignment_data$init, envir = e)
  if(!is.null(init_func)){
      R.utils::withSeed({
        ret_list = init_func(assignment_data, id, seed, solutions, e)
      },
      seed0)
  }else{
    ret_list = list()
  }
    
  return(ret_list)
    
}) %>% bindCache(input$assignment, input$id, input$seed, input$solutions)
```


```{r context="render"}
uiOutput("buttonBox", style = "width: 100%; margin: auto;")
```

```{r context="server"}

output$buttonBox <- renderUI({
  
  req(input$assignment)
  
  assignment = input$assignment
  assignment_data = all_assignment_data[[assignment]]
  
  e = new.env()
  flexTeaching:::sourceAll(assignment_data, e)
  
  bn = assignment_data$buttons

  if(is.null(bn)) return()
  
  if(!exists(bn, envir = e)) return()
  bs = get(bn, envir = e)
  
  button_reactives = list()

  bl = lapply(names(bs), function(b){
    button_reactives[[b]] = reactive({
      shinybusy::show_modal_spinner(text = "Creating file...")
      fc = bs[[b]]$f(
        assignment_data,
        input$id,
        input$seed,
        input$solutions,
        input$format,
        init_list())
      shinybusy::remove_modal_spinner()
      return(fc)
    }) %>% bindCache(input$assignment, input$id, input$seed, input$solutions, input$format, b)
    
    output[[glue::glue("button_{b}")]] <- downloadHandler(
      filename = function() {
        button_reactives[[b]]()$fn
      },
      content = function(f) {
        d = button_reactives[[b]]()$d
        con = file(description = f, open = "wb")
        writeBin(object = d, con = con)
        close(con)
      }
    )
    
    shiny::downloadButton(glue::glue("button_{b}"), label=bs[[b]]$label,
                          icon = icon(bs[[b]]$icon))
  })
  
  do.call(tagList, bl)
})
```



### Assignment

```{r context="render"}
uiOutput("assignmentBox")
```

```{r context="server"}
render_out <- reactive({
  
  req(input$assignment)
  assignment = input$assignment
  assignment_data = all_assignment_data[[assignment]]
  
  id = input$id
  seed = input$seed
  solutions = input$solutions
  
  i = init_list()
  
  e = new.env()
  flexTeaching:::sourceAll(assignment_data, e)
  
  html = flexTeaching:::compilePage(assignment_data, id, seed, solutions, e, i)
  
 return(html)
  
}) %>%
  bindCache(input$assignment, input$id, input$seed, input$solutions)
```

```{r context="server"}
output$assignmentBox <- renderUI({
  withMathJax(render_out())
})
```


<script>
$(document).ready(function () {
  $("#admin_panel").hide();
  $("#show_admin").on("click", function() {
    $("#admin_panel").toggle();
  });
});
</script>

