---
title: "Assignment data download"
output: 
  flexdashboard::flex_dashboard:
    theme: united
    orientation: row
    css: ["css/assignments.css"]
    includes:
      in_header: tmp/headers.html
runtime: shiny
---

```{r setup, include=FALSE}
require(flexdashboard)
        
read.secret.from.file = TRUE

source('settings.R')
writeHeaders("tmp/headers.html")

assignments = getAssignments()
tmp = new.env()
values = reactiveValues(assignment_list = list())

```


```{r}
require(shinyjs)
useShinyjs(rmd=TRUE)

observeEvent(input$seed, {
  observe({
    query = getQueryString()
    ID = query[['ID']]
    ID_active = query[['ID_active']]
    secret = query[['secret']]
    secret_active = query[['secret_active']]
    query_assignment = query[['assignment']]

    if (!is.null(ID)) {
      updateTextInput(session, 'seed', value = ID)
    }
    if (!is.null(secret) & !read.secret.from.file) {
      updateTextInput(session, 'secret', value = secret)
    }
    if (!is.null(query_assignment)) {
      updateSelectInput(session, 'assignment', selected = query_assignment)
    }


    if (!is.null(ID_active)) {
      if (ID_active == '0') {
        disable('seed')
      }
    }
    
    if (!is.null(secret_active) & !read.secret.from.file) {
      if (secret_active == '0') {
        disable('secret')
      }
    }
    
  })
}, once = TRUE)
```



Column {.sidebar}
-----------------------------------------------------------------------

```{r}

selectInput("assignment", label="Assignment", 
            choices = assignments)

textInput("seed", label = "ID number:", width = "150px", placeholder = "Student_ID", value = "Student_ID")

if(!read.secret.from.file){
  textInput("secret", label = "Secret:", width = "150px", placeholder = "s3Cr34", value = "s3Cr34")
}

selectInput("data_format", label="Data format", 
            choices = c("SPSS","Excel","R data","csv"))


getSecret <- function(){
  s = readLines("secret")
  ifelse(read.secret.from.file, s[length(s)],input$secret)
}

observeEvent(input$assignment,{
  
  source(
    paste0("assignments/",input$assignment,"/assignment.R"),
    local = tmp, chdir = TRUE)
  
  values$assignment_list = as.list(tmp)
  
})


```

Row  {data-height=60}
------------------------------------
    
### Data 
    
```{r}

renderUI({
  
  secret = getSecret()
  assignmentDir = paste0("assignments/",input$assignment)
  assignment_time(assignmentDir, secret)

  str = getURIdata(trimws(input$seed), getSecret(), input$data_format, values$assignment_list, session)
  HTML(str)
})
```

Row 
-------------------------------------
    
### Assignment
    
```{r}

renderUI({

  secret = getSecret()
  assignmentDir = paste0("assignments/",input$assignment)
  assignment_time(assignmentDir, secret)

  res = values$assignment_list$getAssignment(trimws(input$seed), secret, assignmentDir, solutions = FALSE)
  
  return(withMathJax(includeHTML(res)))

  
})

```
   

    
