---
title: flexTeaching
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    favicon: '../app/www/favicon.ico'
    logo: '../app/www/wave.svg'
    css: ["../app/www/fingerprint.css", "../app/www/logo.css", "../app/www/fixes.css", "../app/www/practice.css"]
    includes:
      in_header: !expr flexTeaching:::writeHeaders()
---


```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(htmltools)

```


Column {.sidebar}
-----------------------------------------------------------------------

```{r child="children/sidebar_main.Rmd"}
```

Column
------------------------------------


```{r child="children/content.Rmd"}
```



```{r}
tags$script(
  glue::glue("$(function() {{ jdenticon.updateSvg('#flexteaching-fingerprint', '{seed}'); }});")
)
```

```{js}
// See https://stackoverflow.com/a/30106551/1129889
function b64DecodeUnicode(str) {
  // Going backwards: from bytestream, to percent-encoding, to original string.
  return decodeURIComponent(
    atob(str)
      .split('')
      .map(function(c) {
            return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
        })
        .join(''));
}

function makeContentVisible(){
  // check to see if flexdashboard init has run
  // if it has, the parent of dashboard-container will not be <body>
  const flexInit = !$('#dashboard-container').parent().is('body');
  
  // Also check to see if mathjax is defined
  const mathjaxInit = typeof MathJax !== 'undefined'
  // if so, decode the content and make visible
    
  if(flexInit & mathjaxInit){
  	const uri_content = $('#hidden_content').text();
  	const content = b64DecodeUnicode(uri_content);
      
    $('#hidden_content')
      .css('display', 'block')
      .html(content)
      .parents('.chart-stage')
      		.css('overflow','scroll');
    MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
  }else{
    setTimeout(makeContentVisible, 200);
  }
}

$(function() { makeContentVisible(); });
```

