```{r context="server"}

assignment_accessible = reactive({
    
  req(input$assignment)

  assignment = input$assignment
  assignment_data = all_assignment_data[[assignment]]
  
  assignment_data$restrict_before<Sys.time()
  
})

```

```{r context="server"}
init_list = reactive({
  
  req(input$assignment, seed(), entry())

  assignment = input$assignment
  assignment_data = all_assignment_data[[assignment]]
  
  fmt = flexTeaching::pkg_options()$date_format_prnt
  
  validate(
    need(assignment_accessible() | cache_mode(), 
         glue::glue("This assignment will not be available until {strftime(assignment_data$restrict_before, format = fmt)}."))
  )
  
  validate(
    need(!assignment_data$exam || entry() != "solve" || ( seedMatches() & assignment_data[['exam_practice']] ), 
          "This assignment is not available in practice mode."
         )
  )

  id = input$id
  seed = seed()
  solutions = solutions()

  salt = assignment_data$`data-salt`
  seed0 = flexTeaching:::assignmentSeed(id, seed, salt)
  
  # Make parent .GlobelEnv so that apps will not have access to shiny
  # variables; prevents some sneaky hacks like entering R code into
  # text inputs
  future_promise({
    e = new.env(parent = .GlobalEnv)
  
    flexTeaching:::sourceAll(assignment_data, e)
  
    if(!is.null(assignment_data$init)){
      init_func = get(assignment_data$init, envir = e)
      R.utils::withSeed({
        ret_list = init_func(assignment_data, id, seed, solutions, e)
      },
      seed0)
    }else{
      ret_list = list()
    }
    return(ret_list)
  }, seed = NULL)
    
}) %>% bindCache(input$assignment, input$id, seed(), solutions(), assignment_accessible() || cache_mode(), entry(), seedMatches())
```


```{r context="render"}
uiOutput("buttonBox", style = "width: 100%; margin: auto;")
```

```{r context="server"}

output$buttonBox <- renderUI({
  
  req(input$assignment, entry())
  
  assignment = input$assignment
  assignment_data = all_assignment_data[[assignment]]
  
  req(
    assignment_accessible(),
    !assignment_data$exam || entry() != "solve" || ( seedMatches() & assignment_data[['exam_practice']] )
    )
  
  solutions = solutions()
  
  # Make parent .GlobelEnv so that apps will not have access to shiny
  # variables; prevents some sneaky hacks like entering R code into
  # text inputs
  e = new.env(parent = .GlobalEnv)
  
  flexTeaching:::sourceAll(assignment_data, e)
  
  bn = assignment_data$buttons

  req(
    !is.null(bn),
    exists(bn, envir = e)
    )
  
  bs = get(bn, envir = e)
  
  button_reactives = list()
  
  id_ = input$id
  seed_ = seed()
  format_ = input$format
  entry_ = entry()
  
  init_list() %...>% {
    bl = lapply(names(bs), function(b){
      button_reactives[[b]] = reactive({
        init_list = .
        future_promise(
          {
            bs[[b]]$f(
              assignment_data,
              id_,
              seed_,
              solutions,
              format_,
              init_list,
              entry_
            )
          },
        seed = NULL)
    }) %>% bindCache(input$assignment, input$id, seed(), solutions(), input$format, b, assignment_accessible(), entry(), seedMatches())
    
    output[[glue::glue("button_{b}")]] <- downloadHandler(
      filename = function() {
        init_list = .
        bs[[b]]$fn(
            assignment_data,
            id_,
            seed_,
            solutions,
            format_,
            init_list,
            entry_
          )
      },
      content = function(f) {
        con = file(description = f, open = "wb")
        d = button_reactives[[b]]() %>%
          catch(function(error){
            err_text = sprintf("There was an error creating the file. %s", paste(error))
            shinyWidgets::sendSweetAlert(
              session = session,
              title = "Error...",
              text = err_text,
              type = "error"
            )
            stop(err_text)
            }, tee = TRUE) %...>%
          `[[`('d') %...>% 
          { writeBin(object = ., con = con); close(con) }
      }
    )
    
    shiny::downloadButton(glue::glue("button_{b}"), label=bs[[b]]$label,
                          icon = icon(bs[[b]]$icon))
  })
  
  do.call(tagList, bl)
  }
})
```



### Assignment

```{r context="render"}
uiOutput("assignmentBox")
```

```{r context="server"}
render_out <- reactive({
  
  req(input$assignment, seed(), entry())
  assignment = input$assignment
  assignment_data = all_assignment_data[[assignment]]
  
  id = input$id
  seed = seed()
  solutions = solutions()
  
  init_list() %...>% {
  
    e = new.env(parent = .GlobalEnv)
    flexTeaching:::sourceAll(assignment_data, e)
  
    future_promise({
      flexTeaching:::compilePage(assignment_data, id, seed, solutions, e, .) 
    }, 
    seed = NULL,
    )  %...>%
    withMathJax()
  }
  
}) %>%
  bindCache(input$assignment, input$id, seed(), solutions(), assignment_accessible() || cache_mode(), entry(), seedMatches())
```

```{r context="server"}
output$assignmentBox <- renderUI({
  render_out()
})
```

```{r context="server"}
identicon_obs <- observe({
  
  req(input$assignment, seed(), entry())
  assignment = input$assignment
  assignment_data = all_assignment_data[[assignment]]
  
  # Identicon
  id = input$id
  seed = seed()
  salt = assignment_data$`data-salt`
  seed0 = flexTeaching:::assignmentSeed(id, seed, salt)
  if(assignment_accessible()){
    shinyjs::runjs(glue::glue("jdenticon.updateSvg('#flexteaching-fingerprint', '{seed0}');"))
  }else{
    shinyjs::runjs("$('#flexteaching-fingerprint').empty();")
  }
  
})
```


```{r context="server"}
observeEvent(render_out(), {
  
  req(input$assignment, seed(), entry())
  assignment = input$assignment
  assignment_data = all_assignment_data[[assignment]]
  
  req(
    assignment_accessible(),
    !assignment_data$exam || entry() != "solve" || ( seedMatches() & assignment_data[['exam_practice']] )
  )

  # Loading javascript
  req(!is.null(assignment_data[['on-load']]))
  
  js_content = gsub(pattern = "\"", replacement = "\\\"", x = assignment_data[['on-load']],
                    fixed = TRUE)
  
  init_list() %...>% {
    e = new.env(parent = .GlobalEnv)
    e$.flexteach_info = .
    js_expr = parse(text = glue::glue('glue::glue("{js_content}")'))
  
    js_parsed = tryCatch(eval(expr = js_expr, envir = e),
      error = function(c){
        # Using paste0 instead of glue to prevent code injection from input
        error_text = paste0(
          "Problem parsing javascript code on load of assignment ",
          input$assignment,
          ": ",
          c
        )
        safeError(error_text)
      }
    )

    if(!is.null(js_parsed) & length(js_parsed)>0)
      shinyjs::runjs(js_parsed)
  }
})
```
