<script src='https://unpkg.com/survey-jquery'></script>


```{r context="server"}
# You can change the package options here.

# flexTeaching::pkg_options(start_practice_message = "")
# flexTeaching::pkg_options(secret_filename = "")

```

```{r context="server"}
l = readLines(flexTeaching::pkg_options('secret_filename'))
masterseed = trimws(l[length(l)])
```

```{r setup, include=FALSE, context="setup"}
library(promises)
library(future)
plan(multisession)

library(flexdashboard)
library(magrittr)
library(dplyr)
library(shinyWidgets)
library(flexTeaching)
knitr::opts_chunk$set(echo = FALSE)

all_assignment_data =  flexTeaching:::getAssignments(simple = FALSE)

globals = new.env()
```

```{r, echo=FALSE}
shiny::addResourcePath("shinyjs", system.file("srcjs", package = "shinyjs"))
```

```{r, context="server"}
shinyjs::useShinyjs(html = TRUE)

cache_mode = reactive({
  query = getQueryString()
  'cache_mode' %in% names(query)
})
```
<script src="shinyjs/inject.js"></script>

```{r cache, eval = params$cache_setup, context="server"}
shinyOptions(
  cache = cachem::cache_disk(
    dir = "./my_app_cache",
    max_size = 512 * 1024^2,
    max_age = 60 * 60 * 24 * 10
    )
)
```
