
```{r context="render"}

uiOutput("solutionsbox")

htmltools::tags$div(
  "Show admin",
  id = "show_admin"
)

htmltools::tags$div(
  uiOutput("seedbox"),
  uiOutput("clipseed"),
  htmltools::tags$hr(),
  uiOutput("masterseedbox"),
  id = "admin_panel"
)

```

```{r context="server"}
# This value just exists to tell us whether the masterseed has changed
# from its default of "". Doesn't need to be reactive
changed_master = FALSE

output$seedbox <- renderUI({
  query = getQueryString()
  
  curr_seed = isolate(input$seed)
  
  # initial setting from query string
  if(is.null(input$masterseed) || is.null(input$assignment)){
    seed0 = if ('seed' %in% names(query)) query[['seed']] else flexTeaching::pkg_options()$initial_seed
    globals$first_seed = seed0
  }else{ # not initial value
    changed_master <<- changed_master || input$masterseed != ""
    
    salt = all_assignment_data[[input$assignment]]$`seed-salt`
    seed0 = flexTeaching:::animalSeed(input$masterseed, salt)
    
    # IF      we've changed the master seed and the master seed is blank, set it back
    #         to the default.
    # ELSE IF the masterseed is blank and we haven't changed it (that is, it 
    #         remains the default) then keep the seed at its current value.
    # ELSE    we need to freeze the reactive value temporarily so it the first change
    #         doesn't get picked up (before the assignment has changed)
    if(is.null(curr_seed) || (changed_master & input$masterseed == "")){
      seed0 = globals$first_seed
    }else if (input$masterseed == "" & !changed_master){
      seed0 = curr_seed
    } else {
      freezeReactiveValue(input, "seed")
    }
  }
  
  el = textInput("seed", label = "Seed:", width = "150px", value = seed0)
  if('seed_disable' %in% names(query)){
    return(shinyjs::disabled(el))
  }else{
    return(el)
  }
})

output$clipseed <- renderUI({
    rclipboard::rclipButton("clipbtnseed", "Copy seed", input$seed, icon("clipboard"))
  })

output$masterseedbox <- renderUI({
  query = getQueryString()
  mseed = if ('masterseed' %in% names(query)) query[['masterseed']] else ""
  el = textInput("masterseed", label = "Master seed:", width = "150px", value = mseed)
  if('masterseed_disable' %in% names(query)){
    return(shinyjs::disabled(el))
  }else{
    return(el)
  }
})

output$solutionsbox <- renderUI({
  query = getQueryString()
  sol = if ('solutions' %in% names(query)) query[['solutions']] else FALSE
  sol = as.logical(sol)
  el = checkboxInput("solutions", label = "Show solutions?", value = as.logical(sol))
  if('solutions_disable' %in% names(query)){
    return(shinyjs::disabled(el))
  }else{
    return(el)
  }
})
```

```{r context="server"}

shiny::outputOptions(output, 'seedbox', suspendWhenHidden=FALSE)
shiny::outputOptions(output, 'masterseedbox', suspendWhenHidden=FALSE)
shiny::outputOptions(output, 'clipseed', suspendWhenHidden=FALSE)

```

