
```{r context="render"}
uiOutput("entrybox")
uiOutput("assignmentbox")
uiOutput("idbox")

# Identicon
includeScript(path = system.file("app/www/jdenticon.min.js", package = "flexTeaching"))
tags$div(
  title="Fingerprint", class="flexteaching-fingerprint-container",
  tags$svg(id="flexteaching-fingerprint")
)

uiOutput("formatbox")
```

```{r context="server"}

session$allowReconnect(TRUE)

output$entrybox <- renderUI({
  query = getQueryString()
  solve_mode = 'solve' %in% names(query)
  disabled = 'entry_disable' %in% names(query)
  el = switchInput(
    "entry",
    onStatus = "success", 
    offStatus = "danger",
    onLabel = "Practice",
    offLabel = "Assignment",
    label = "Mode",
    value = solve_mode,
    handleWidth = 125,
    labelWidth = 65,
    inline = TRUE,
    width = "200px",
    disabled = disabled
  )
  return(el)
})

## Warning(s) when switching modes
observeEvent(entry(), {

  if(entry()=='solve'){
    message = flexTeaching::pkg_options("start_practice_message")
    shinyjs::runjs("$('.navbar').addClass('navbar-practice');")
    shinyjs::runjs("$('#section-column.sidebar').addClass('sidebar-practice');")
    shinyjs::runjs("$('span.navbar-brand').addClass('title-practice');")
  }
  
  if(entry()=='download'){
    message = flexTeaching::pkg_options("start_assignment_message")
    shinyjs::runjs("$('.navbar').removeClass('navbar-practice');")
    shinyjs::runjs("$('#section-column.sidebar').removeClass('sidebar-practice');")
    shinyjs::runjs("$('span.navbar-brand').removeClass('title-practice');")
  }
  
  req(message)
  
  sendSweetAlert(
    session = session,
    title = "Information",
    text = message,
    type = "info"
  )
}, ignoreInit = TRUE)


output$idbox <- renderUI({
  query = getQueryString()
  seed = if ('id' %in% names(query)) query[['id']] else ""
  el = textInput("id", label = "ID:", width = "150px", value = seed, placeholder = "Your ID")
  if('id_disable' %in% names(query)){
    return(shinyjs::disabled(el))
  }else{
    return(el)
  }
})

# This code "invalidates" the seed if we know that we're going to compute
# new seed when the assignment changes. This prevents double execution of 
# the init_list
# Note that validSeed is global and is set later with `<<-`
assignment <- eventReactive(input$assignment, {
  req(entry)
  if(!is.null(input$masterseed) && input$masterseed != "" && entry == 'solve')
    validSeed <<- FALSE
  return(input$assignment)
})

output$assignmentbox <- renderUI({
  
  req(entry())
  
  curr_assignment = isolate(input$assignment)
  
  query = getQueryString()
  if(is.null(curr_assignment)){
    assignment = query[['assignment']]
  }else{
    assignment = curr_assignment
  }
  cat_regex   = query[['category']]
  if(is.null(cat_regex))
    cat_regex = ""
  
  flexTeaching:::getAssignments() %>%
    mutate(
      hidden = case_when(
        !grepl(pattern = cat_regex, x = category) ~ TRUE,
        TRUE ~ hidden
      ) # Hide ones that don't match category regexp
    ) %>%
    {
      if(is.null(assignment)){
        filter(., !hidden)
      }else{
        filter(., !hidden | (shortname == !!assignment))
      } # Filter out the hidden ones, except if we've specified it in the query string
    } %>%
    split(.$category) %>%
    purrr::map(function(el){
      z = pull(el, shortname)
      names(z) = pull(el, title)
      return(z)
    }) -> assignments

  if('assignment_disable' %in% names(query)){
    el = selectInput("assignment", label = "Assignment:", width = "150px", choices = assignments, selected = assignment)
    return(shinyjs::disabled(el))
  }else{
    
    ## Get relevant settings
    ## This is ugly code, revisit and combine with above to shorten
    flexTeaching:::getAssignments(simple=FALSE) %>% 
      `[`(unlist(assignments)) %>%
      purrr::map_df(function(el){
        tibble(shortname = el$shortname,
               available = el$restrict_before < Sys.time(),
               exam = el$exam
               )
        }) %>%
      mutate(
        icon = case_when(
          !available ~ "glyphicon-hourglass",
          exam ~ "glyphicon-pencil",
          TRUE ~ ""
          ),
        style = case_when(
          !available ~ "color: lightcoral;",
          exam & entry() == 'solve' ~ "color: lightcoral;",
          TRUE ~ ""
          )
        ) -> icon_prep
    
    el = shinyWidgets::pickerInput(
      "assignment", 
      label = "Assignment:", 
      width = "150px", 
      choices = assignments,
      selected = assignment,
      options = list(`live-search`=TRUE),
      choicesOpt = list(
        style = icon_prep$style,
        icon = icon_prep$icon
        )
      )
    return(el)
  }
})

output$formatbox <- renderUI({
  query = getQueryString()
  format = if ('format' %in% names(query)) query[['format']] else NULL
  el = selectInput("format", label = "Data format:", choices = names(flexTeaching:::formats), selected = format)
  if('format_disable' %in% names(query)){
    return(shinyjs::disabled(el))
  }else{
    return(el)
  }
})


```
